name: DigitalOcean Server Deploy using SCP

on: 
  push:
    branches: 
      - master

env:
 USER: ${{secrets.DIGITALOCEAN_USER}}
 PASS: ${{secrets.DIGITALOCEAN_PASS}}
 DIR: ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the app
      run: |
        php -r "file_exists('.env') || copy('.env.example','.env');"
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        php artisan key:generate
    - name: Deploy
      run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . ${{env.USER}}@buildpc.software:/home/${{env.USER}}/actionTest
      env:
        DB_CONNECTION: mysql
        DB_HOST: buildpc.software
        DB_PORT: 3306
        DB_DATABASE: ${{secrets.DIGITALOCEAN_DB}}
        DB_USERNAME: ${{secrets.DIGITALOCEAN_DB_USER}}
        DB_PASS: ${{secrets.DIGITALOCEAN_DB_PASS}}
        
