#gotta work rn
name: DigitalOcean_Deploy_rsync

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Deploy with rsync
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    - name: Get the Files
      run: echo "maybe?"
    - name: Deploy
      uses: BuildPC/rsync-with-ssh-github-actions@master
      with:
        key: ${{secrets.SSH_KEY}}
        host: buildpc.software
        user: ${{secrets.DIGITALOCEAN_USER}}
        port: 22
        destination: ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}
        args: "-c -q -P -z -r --delete --filter 'protect ./public/photos/' --filter 'protect ./storage/'"
        ssh_before: cd ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}
        ssh_after: |
          cd ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}
          composer require "laravel/installer"
          composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
          cp ../private/.env ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}
          php artisan key:generate
          npm install
          npm run production
          chgrp -R www-data ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}
          chmod -R 775 ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}

