name: DigitalOcean Server Deploy using SCP

on: 
  push:
    branches: 
      - master

env:
 USER: ${{secrets.DIGITALOCEAN_USER}}
 PASS: ${{secrets.DIGITALOCEAN_PASS}}
 DIR: ${{secrets.DIGITALOCEAN_DEPLOY_DIR}}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the Files
      run: echo "maybe?"
#     - name: Build the app
#       run: |
#         php -r "file_exists('.env') || copy('.env.example','.env');"
#         composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
#         php artisan key:generate
    - name: Deploy
      uses: alinz/ssh-scp-action@master
      with:
        key: ${{secrets.SSH_KEY}}
        host: buildpc.software
        user: ${{ env.USER }}
        port: 22
        ssh_before: |
          cd ${{env.DIR}}
          rm -rf *
        scp: |
          -r * ${{env.USER}}@buildpc.software:${{env.DIR}}
#       run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . ${{env.USER}}@buildpc.software:/home/${{env.USER}}/actionTest
        ssh_after: |
          cd ${{env.DIR}}
          composer require "laravel/installer"
          composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
          cp ../private/.env ${{env.DIR}}
          php artisan key:generate
          npm install
          npm run production
          chgrp -R www-data ${{env.DIR}}
          chmod -R 775 ${{env.DIR}}
        
